// export const CATEGORIES = [
//   { id: 1, title_ar: "متاجر إلكترونية", title_en: "E-commerce Stores" },
//   { id: 2, title_ar: "مواقع الشركات", title_en: "Corporate Websites" },
//   { id: 3, title_ar: "تسويق رقمي", title_en: "Digital Marketing" },
//   { id: 4, title_ar: "تطبيقات الجوال", title_en: "Mobile Apps" },
// ];

export const CATEGORIES = [
  {
    id: 1,
    title_ar: "متاجر إلكترونية",
    title_en: "E-commerce Stores",
    title_fr: "Boutiques en ligne",
    title_de: "Online-Shops",
    title_es: "Tiendas en línea",
    title_it: "Negozi online",
    title_tr: "E-ticaret Mağazaları",
    title_hi: "ई-कॉमर्स स्टोर",
    title_bn: "ই-কমার্স স্টোর",
    title_ur: "ای کامرس اسٹورز",
  },
  {
    id: 2,
    title_ar: "مواقع الشركات",
    title_en: "Corporate Websites",
    title_fr: "Sites d'entreprise",
    title_de: "Unternehmens-Websites",
    title_es: "Sitios web corporativos",
    title_it: "Siti web aziendali",
    title_tr: "Kurumsal Web Siteleri",
    title_hi: "कॉर्पोरेट वेबसाइटें",
    title_bn: "করপোরেট ওয়েবসাইট",
    title_ur: "کارپوریٹ ویب سائٹس",
  },
  {
    id: 3,
    title_ar: "تسويق رقمي",
    title_en: "Digital Marketing",
    title_fr: "Marketing digital",
    title_de: "Digitales Marketing",
    title_es: "Marketing digital",
    title_it: "Marketing digitale",
    title_tr: "Dijital Pazarlama",
    title_hi: "डिजिटल मार्केटिंग",
    title_bn: "ডিজিটাল মার্কেটিং",
    title_ur: "ڈیجیٹل مارکیٹنگ",
  },
  {
    id: 4,
    title_ar: "تطبيقات الجوال",
    title_en: "Mobile Apps",
    title_fr: "Applications mobiles",
    title_de: "Mobile Apps",
    title_es: "Aplicaciones móviles",
    title_it: "Applicazioni mobili",
    title_tr: "Mobil Uygulamalar",
    title_hi: "मोबाइल ऐप्स",
    title_bn: "মোবাইল অ্যাপস",
    title_ur: "موبائل ایپس",
  },
];
