-- =====================================================================
--  TRAFYEK BLS — ضبط قاعدة بيانات Supabase
--  ------------------------------------------------------------------
--  شغّل هذا الملف كاملاً مرة واحدة من:
--      Supabase Dashboard > SQL Editor > New query > Run
--
--  الملف مكتوب كـ "هجرة" (migration) على قاعدة البيانات الحالية:
--    • ينشئ الجداول الناقصة فقط (create table if not exists)
--    • يضيف الأعمدة الناقصة فقط (add column if not exists)
--    • لا يحذف أي عمود أو صف موجود
--    • آمن لإعادة التشغيل أكثر من مرة
--
--  ⚠️ الأهم: القسم (5) يغلق ثغرة أمنية حقيقية.
--     حالياً مفتاح anon — وهو مفتاح عام يظهر في متصفح كل زائر —
--     يستطيع تعديل وحذف كل صفوف كل الجداول، وقراءة كل رسائل التواصل.
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) دالة مشتركة لتحديث updated_at تلقائياً
-- ---------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- =====================================================================
-- 2) الجداول (تُنشأ فقط إن لم تكن موجودة)
-- =====================================================================

create table if not exists public.site_settings (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now()
);

create table if not exists public.categories (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now()
);

create table if not exists public.products (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now()
);

create table if not exists public.projects (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now()
);

create table if not exists public.blogs (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now()
);

create table if not exists public.partners (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now()
);

create table if not exists public.pages (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id              bigint generated by default as identity primary key,
  created_at      timestamptz not null default now()
);


-- =====================================================================
-- 3) الأعمدة — تُضاف الناقصة فقط
--    (الأعمدة المعلَّم عليها "ناقص حالياً" هي التي يحتاجها الكود ولم تكن
--     موجودة في قاعدة البيانات الحالية)
-- =====================================================================

-- 3.1 إعدادات الموقع (صف واحد) — src/lib/siteSettings.js
alter table public.site_settings
  add column if not exists description_ar text not null default '',
  add column if not exists description_en text not null default '',
  add column if not exists image_url      text,
  add column if not exists whatsapp       text,
  add column if not exists phone          text,
  add column if not exists email          text,
  add column if not exists instagram      text,
  add column if not exists tiktok         text,
  add column if not exists snapchat       text,
  add column if not exists x_account      text,
  add column if not exists updated_at     timestamptz not null default now();

-- 3.2 التصنيفات = الخدمات — /services و /services/[id] و /services/[id]/[city]
alter table public.categories
  add column if not exists title_ar            text,
  add column if not exists title_en            text,
  add column if not exists description_ar      text,
  add column if not exists description_en      text,
  add column if not exists long_description_ar text,
  add column if not exists long_description_en text,
  add column if not exists image_url           text,
  add column if not exists "order"             integer not null default 0,
  -- ناقص حالياً: يستخدمه sitemap.js لحساب lastModified
  add column if not exists updated_at          timestamptz not null default now();

-- 3.3 المنتجات
alter table public.products
  add column if not exists title_ar       text,
  -- ناقص حالياً: لوحة التحكم أصبحت ثنائية اللغة مثل باقي الجداول
  add column if not exists title_en       text,
  add column if not exists description_ar text,
  add column if not exists description_en text,
  add column if not exists price          numeric(12,2),
  add column if not exists image_url      text,
  add column if not exists category_id    bigint,
  add column if not exists "order"        integer not null default 0,
  add column if not exists updated_at     timestamptz not null default now();

-- 3.4 المشاريع (سابقة الأعمال)
alter table public.projects
  add column if not exists title_ar       text,
  add column if not exists title_en       text,
  add column if not exists description_ar text,
  add column if not exists description_en text,
  add column if not exists project_link   text,
  add column if not exists image_url      text,
  add column if not exists category_id    bigint,
  add column if not exists is_featured    boolean not null default false,
  add column if not exists "order"        integer not null default 0,
  add column if not exists updated_at     timestamptz not null default now();

-- 3.5 المقالات
alter table public.blogs
  add column if not exists title_ar       text,
  add column if not exists title_en       text,
  add column if not exists description_ar text,
  add column if not exists description_en text,
  add column if not exists category_ar    text,
  add column if not exists category_en    text,
  add column if not exists image_url      text,
  -- ناقص حالياً: يستخدمه sitemap.js و JSON-LD (dateModified)
  add column if not exists updated_at     timestamptz not null default now();

-- 3.6 الشركاء
alter table public.partners
  add column if not exists image_url  text,
  add column if not exists "order"    integer not null default 0,
  add column if not exists updated_at timestamptz not null default now();

-- 3.7 الصفحات الثابتة
alter table public.pages
  add column if not exists slug       text,
  add column if not exists title_ar   text not null default '',
  add column if not exists title_en   text not null default '',
  add column if not exists content_ar text not null default '',
  add column if not exists content_en text not null default '',
  add column if not exists updated_at timestamptz not null default now();

-- 3.8 رسائل التواصل
alter table public.contact_messages
  add column if not exists name    text,
  add column if not exists email   text,
  add column if not exists phone   text,
  add column if not exists message text,
  -- عمود مساعد اختياري لتمييز الرسائل المقروءة لاحقاً
  add column if not exists is_read boolean not null default false;


-- =====================================================================
-- 4) القيود والفهارس والمشغّلات (triggers)
-- =====================================================================

-- 4.1 pages.slug فريد — مطلوب لأن PageViewer يستخدم upsert on conflict (slug)
create unique index if not exists pages_slug_key on public.pages (slug);

-- 4.2 المفاتيح الأجنبية للتصنيفات
--     on delete restrict: لا يُحذف تصنيف مرتبط بمنتجات (الكود يعالج الخطأ 23503)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'products_category_id_fkey'
  ) then
    alter table public.products
      add constraint products_category_id_fkey
      foreign key (category_id) references public.categories (id) on delete restrict;
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'projects_category_id_fkey'
  ) then
    alter table public.projects
      add constraint projects_category_id_fkey
      foreign key (category_id) references public.categories (id) on delete set null;
  end if;
end
$$;

-- 4.3 الفهارس
create index if not exists categories_order_idx     on public.categories ("order");
create index if not exists products_order_idx       on public.products ("order");
create index if not exists products_category_idx    on public.products (category_id);
create index if not exists projects_order_idx       on public.projects ("order");
create index if not exists projects_category_idx    on public.projects (category_id);
create index if not exists projects_featured_idx    on public.projects (is_featured) where is_featured;
create index if not exists partners_order_idx       on public.partners ("order");
create index if not exists blogs_created_at_idx     on public.blogs (created_at desc);
create index if not exists contact_created_at_idx   on public.contact_messages (created_at desc);

-- 4.4 مشغّلات updated_at
do $$
declare
  t text;
begin
  foreach t in array array[
    'site_settings','categories','products','projects','blogs','partners','pages'
  ] loop
    execute format('drop trigger if exists set_%s_updated_at on public.%I', t, t);
    execute format(
      'create trigger set_%s_updated_at before update on public.%I
       for each row execute function public.set_updated_at()', t, t
    );
  end loop;
end
$$;


-- =====================================================================
-- 5) ⚠️ الأمان: تفعيل RLS وضبط الصلاحيات
--    ------------------------------------------------------------------
--    قبل هذا القسم: أي زائر يملك مفتاح anon (وهو ظاهر في كود المتصفح)
--    يستطيع حذف وتعديل كل شيء، وقراءة كل رسائل التواصل.
--
--    بعده:
--      • الزائر (anon)        : قراءة المحتوى فقط + إرسال رسالة تواصل
--      • المسجّل (authenticated): صلاحية كاملة = لوحة التحكم
--      • service_role          : يتجاوز RLS دائماً (يُستخدم في الخادم فقط)
-- =====================================================================

alter table public.site_settings    enable row level security;
alter table public.categories       enable row level security;
alter table public.products         enable row level security;
alter table public.projects         enable row level security;
alter table public.blogs            enable row level security;
alter table public.partners         enable row level security;
alter table public.pages            enable row level security;
alter table public.contact_messages enable row level security;

-- إزالة أي سياسات مفتوحة قديمة على جداول المحتوى ثم إنشاء سياسات محكمة
do $$
declare
  t   text;
  pol record;
  content_tables text[] := array[
    'site_settings','categories','products','projects','blogs','partners','pages'
  ];
begin
  foreach t in array content_tables loop
    -- حذف كل السياسات السابقة على الجدول
    for pol in
      select policyname from pg_policies
      where schemaname = 'public' and tablename = t
    loop
      execute format('drop policy %I on public.%I', pol.policyname, t);
    end loop;

    -- قراءة عامة (الموقع يعرض هذا المحتوى للزوار)
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true)',
      t || '_public_read', t
    );

    -- كتابة/تعديل/حذف للمستخدم المسجّل فقط (لوحة التحكم)
    execute format(
      'create policy %I on public.%I for insert to authenticated with check (true)',
      t || '_auth_insert', t
    );
    execute format(
      'create policy %I on public.%I for update to authenticated using (true) with check (true)',
      t || '_auth_update', t
    );
    execute format(
      'create policy %I on public.%I for delete to authenticated using (true)',
      t || '_auth_delete', t
    );
  end loop;
end
$$;

-- رسائل التواصل: الزائر يُرسل فقط ولا يقرأ شيئاً
do $$
declare
  pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'contact_messages'
  loop
    execute format('drop policy %I on public.contact_messages', pol.policyname);
  end loop;
end
$$;

create policy contact_messages_public_insert
  on public.contact_messages for insert
  to anon, authenticated with check (true);

create policy contact_messages_auth_read
  on public.contact_messages for select
  to authenticated using (true);

create policy contact_messages_auth_update
  on public.contact_messages for update
  to authenticated using (true) with check (true);

create policy contact_messages_auth_delete
  on public.contact_messages for delete
  to authenticated using (true);


-- =====================================================================
-- 6) دالة إحصائيات لوحة التحكم
--    يستدعيها: supabase.rpc("get_dashboard_stats")
--    ترجع: { products, categories, projects, blogs, partners, messages }
-- =====================================================================
create or replace function public.get_dashboard_stats()
returns json
language sql
security definer
set search_path = public
stable
as $$
  select json_build_object(
    'products',   (select count(*) from public.products),
    'categories', (select count(*) from public.categories),
    'projects',   (select count(*) from public.projects),
    'blogs',      (select count(*) from public.blogs),
    'partners',   (select count(*) from public.partners),
    'messages',   (select count(*) from public.contact_messages)
  );
$$;

-- لا تُتاح للزوار: عدد الرسائل معلومة إدارية
revoke all on function public.get_dashboard_stats() from public, anon;
grant execute on function public.get_dashboard_stats() to authenticated;


-- =====================================================================
-- 7) مساحات التخزين (Storage)
--    الأسماء مطابقة تماماً لما يستخدمه الكود.
-- =====================================================================
insert into storage.buckets (id, name, public)
values
  ('site-images', 'site-images', true),
  ('categories',  'categories',  true),
  ('products',    'products',    true),
  ('projects',    'projects',    true),
  ('partners',    'partners',    true),
  ('blogs',       'blogs',       true)
on conflict (id) do update set public = excluded.public;

-- قراءة عامة للصور + رفع/تعديل/حذف للمستخدم المسجّل فقط.
-- ملاحظة: إن ظهر خطأ "must be owner of table objects" فأنشئ نفس السياسات
--         يدوياً من: Storage > Policies في لوحة Supabase.
do $$
declare
  b text;
begin
  foreach b in array array[
    'site-images','categories','products','projects','partners','blogs'
  ] loop
    execute format('drop policy if exists %I on storage.objects', b || '_public_read');
    execute format(
      'create policy %I on storage.objects for select to anon, authenticated using (bucket_id = %L)',
      b || '_public_read', b
    );

    execute format('drop policy if exists %I on storage.objects', b || '_auth_insert');
    execute format(
      'create policy %I on storage.objects for insert to authenticated with check (bucket_id = %L)',
      b || '_auth_insert', b
    );

    execute format('drop policy if exists %I on storage.objects', b || '_auth_update');
    execute format(
      'create policy %I on storage.objects for update to authenticated using (bucket_id = %L) with check (bucket_id = %L)',
      b || '_auth_update', b, b
    );

    execute format('drop policy if exists %I on storage.objects', b || '_auth_delete');
    execute format(
      'create policy %I on storage.objects for delete to authenticated using (bucket_id = %L)',
      b || '_auth_delete', b
    );
  end loop;
end
$$;


-- =====================================================================
-- 8) بيانات لازمة للتشغيل (لا تُكرَّر عند إعادة التشغيل)
-- =====================================================================

-- 8.1 صف الإعدادات الوحيد
insert into public.site_settings (description_ar, description_en)
select
  'ترافيك بلس - شركة تسويق رقمي وتصميم مواقع ومتاجر إلكترونية في السعودية.',
  'Traffic Plus - digital marketing, web and e-commerce development in Saudi Arabia.'
where not exists (select 1 from public.site_settings);

-- 8.2 الصفحات الثلاث التي تربطها القائمة الجانبية والفوتر
--     (/dashboard/pages/<slug>  و  /pages/<slug>)
insert into public.pages (slug, title_ar, title_en)
values
  ('about-us',         'من نحن',          'About Us'),
  ('privacy-policy',   'سياسة الخصوصية',  'Privacy Policy'),
  ('terms-conditions', 'الشروط والأحكام', 'Terms & Conditions')
on conflict (slug) do nothing;

-- 8.3 نسخ عناوين المنتجات إلى العمود الإنجليزي الجديد عند فراغه
--     (حتى لا تظهر المنتجات بلا عنوان في الواجهة الإنجليزية)
update public.products
set title_en = title_ar
where title_en is null and title_ar is not null;


-- =====================================================================
-- 9) (اختياري) قصر لوحة التحكم على حسابات محددة
--    ------------------------------------------------------------------
--    الإعداد أعلاه يعتبر أي حساب في Supabase Auth مسؤولاً.
--    إن كان التسجيل الذاتي (sign-up) مفعّلاً في مشروعك، فعطّله من:
--        Authentication > Providers > Email > Disable "Enable sign ups"
--    أو استخدم الكتلة التالية لقصر الصلاحية على جدول admins.
-- =====================================================================
--
-- create table if not exists public.admins (
--   user_id    uuid primary key references auth.users (id) on delete cascade,
--   created_at timestamptz not null default now()
-- );
-- alter table public.admins enable row level security;
--
-- create or replace function public.is_admin()
-- returns boolean language sql security definer set search_path = public stable
-- as $$ select exists (select 1 from public.admins where user_id = auth.uid()); $$;
--
-- do $$
-- declare t text;
-- begin
--   foreach t in array array[
--     'site_settings','categories','products','projects','blogs','partners','pages',
--     'contact_messages'
--   ] loop
--     execute format('drop policy if exists %I on public.%I', t || '_auth_insert', t);
--     execute format('drop policy if exists %I on public.%I', t || '_auth_update', t);
--     execute format('drop policy if exists %I on public.%I', t || '_auth_delete', t);
--     execute format('create policy %I on public.%I for insert to authenticated with check (public.is_admin())', t || '_auth_insert', t);
--     execute format('create policy %I on public.%I for update to authenticated using (public.is_admin()) with check (public.is_admin())', t || '_auth_update', t);
--     execute format('create policy %I on public.%I for delete to authenticated using (public.is_admin())', t || '_auth_delete', t);
--   end loop;
-- end
-- $$;
--
-- insert into public.admins (user_id)
-- select id from auth.users where email = 'admin@example.com'
-- on conflict do nothing;


-- =====================================================================
-- الخطوات بعد التشغيل:
--   1) Authentication > Users > Add user  → أنشئ حساب المسؤول
--   2) سجّل الدخول من  /ar/login
--   3) تأكد أن أعمدة "التصنيف" في صفحتي المنتجات والمشاريع تعرض القائمة
--   4) (موصى به بشدة) بعد إغلاق RLS، دوّر مفتاح service_role من:
--      Settings > API > Service role  إن كان قد تسرّب في أي وقت.
-- =====================================================================
