import { Cairo, Space_Grotesk, Space_Mono } from "next/font/google";
import "./globals.css";
import AOSProvider from "./AOSProvider";
import { GoogleTagManager } from "@next/third-parties/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

// Cairo is a variable font. Omitting `weight` loads the variable axis as a
// single file instead of one static file per weight.
//
// The previous list was wrong in both directions, measured against actual
// class usage in src/:
//   font-light     (300) — loaded, used 0 times          → pure download waste
//   font-semibold  (600) — NOT loaded, used 43 times     → browser faked it
//   font-extrabold (800) — NOT loaded, used 31 times     → browser faked it
// Synthesised weights are especially poor on Arabic letterforms, where the
// browser smears the strokes of a lighter weight rather than using the real
// design. One variable file is both lighter than five static ones and the only
// version that renders all 74 of those elements correctly.
const cairo = Cairo({
  subsets: ["arabic"],
  display: "swap",
  preload: true,
});

// Latin display faces used by the approved designs for numerals,
// English fragments and technical labels. Not preloaded — Cairo carries
// the running text and these appear only in accent positions.
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
  preload: false,
});

const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space-mono",
  display: "swap",
  preload: false,
});

// meta data
export const metadata = {
  metadataBase: new URL("https://www.trafyekbls.com"),

  title: {
    default:
      "ترافيك بلس | شركة تسويق رقمي في الرياض تصميم المواقع والمتاجر الإلكترونية",
    template: "%s | ترافيك بلس",
  },

  description:
    "ترافيك بلس من شركات التسويق الرقمي الرائدة في السعودية، نقدم خدمات تحسين خرائط جوجل، السيو المحلي SEO، إدارة إعلانات جوجل ومنصات التواصل الاجتماعي، تصميم المواقع والمتاجر الإلكترونية وحلول التسويق الرقمي لزيادة المبيعات وتعزيز نمو الأعمال.",
  keywords: [
    "ترافيك بلس",
    "تصميم مواقع",
    "برمجة مواقع",
    "تصميم متجر إلكتروني",
    "إنشاء متجر سلة",
    "إنشاء متجر زد",
    "تطوير المتاجر الإلكترونية",
    "تحسين محركات البحث",
    "SEO",
    "السيو المحلي",
    "خرائط جوجل",
    "Google Maps SEO",
    "إضافة نشاط تجاري على جوجل",
    "توثيق نشاط تجاري",
    "تصدر نتائج خرائط جوجل",
    "حل مشكلة تعليق نشاط جوجل",
    "إدارة حملات جوجل أدز",
    "التسويق الرقمي",
    "شركة تسويق رقمي",
    "شركة برمجة في السعودية",
    "Next.js",
    "Supabase",
  ],

  // NO `alternates` here on purpose.
  //
  // Next.js inherits metadata from this layout into every page that does not
  // define its own, so a static canonical here was emitted on pages it did not
  // describe. Verified in the built HTML before removal:
  //   GET /ar/ourwork -> <link rel="canonical" href=".../ar">
  //   GET /en/ourwork -> <link rel="canonical" href=".../ar">
  // Every page group without its own generateMetadata — the project pages, the
  // blog index, the CMS pages and the English home page — was asking Google to
  // index the Arabic home page instead of itself.
  //
  // Canonical and hreflang are now built per page via alternatesFor() /
  // buildMetadata() in src/lib/seo.js. Any new page must set them.

  openGraph: {
    title:
      "ترافيك بلس | شركة تسويق رقمي في الرياض وتصميم المواقع والمتاجر الإلكترونية",
    description:
      "حلول احترافية في التسويق الرقمي، تحسين خرائط جوجل، SEO، إدارة الإعلانات، تصميم المواقع والمتاجر الإلكترونية للشركات في السعودية.",

    url: "https://www.trafyekbls.com/ar",

    siteName: "Traffic Plus",

    // NO `images` here. It pointed at /og-image.jpg, which does not exist in
    // public/ — verified with `ls public/og-image.jpg`. Every share card on
    // every page was requesting a 404. The image is now generated by
    // opengraph-image.js in this same folder, which Next applies automatically
    // to every page below it, and which cannot go missing.

    locale: "ar_SA",
    type: "website",
  },

  twitter: {
    card: "summary_large_image",

    title: "ترافيك بلس | تصميم المواقع والمتاجر الإلكترونية والتسويق الرقمي",

    description:
      "نساعد الشركات والمتاجر على النمو عبر المواقع الاحترافية والسيو وخرائط جوجل.",

    // Same as openGraph above: the generated opengraph-image.js supplies this.
  },

  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },

  robots: {
    index: true,
    follow: true,

    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const messages = await getMessages();
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <GoogleTagManager gtmId="GTM-K46W3W6N" />
      <body
        className={`${cairo.className} ${spaceGrotesk.variable} ${spaceMono.variable} bg-white text-slate-900 selection:bg-purple-100 selection:text-purple-900`}
      >
        <NextIntlClientProvider messages={messages}>
          <AOSProvider>
            <main className="min-h-screen">{children}</main>
          </AOSProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
