-- 008 · city landing pages
--
-- Why a table and not a template over lib/cities.js:
-- A page generated by swapping a city name into fixed copy is a doorway page.
-- Google classes that as scaled content abuse, and it is the exact pattern you
-- ruled out. So the schema makes thin pages IMPOSSIBLE TO PUBLISH rather than
-- merely discouraged: `is_published` cannot be set true unless the city-specific
-- fields are actually filled in. The constraint is the whole point of this file.
--
-- Safety: new table only. Nothing existing is touched.
--
-- Review before running. Not applied by the app.

create table if not exists public.city_pages (
  id           bigint generated always as identity primary key,
  -- URL segment, e.g. 'riyadh'. Latin so the path stays clean; the Arabic name
  -- is a separate display field.
  slug         text not null,
  country_code text not null default 'SA',
  region_id    text,

  name_ar      text not null,
  name_en      text not null,

  -- ── The fields below are what make the page NOT a template ────────────────
  -- intro: why this city specifically. Local market, not generic copy.
  intro_ar     text,
  intro_en     text,
  -- something true only of this city: a district, a sector, a local detail
  local_context_ar text,
  local_context_en text,
  -- services that actually matter here, if they differ from the default set
  focus_services text[],
  -- FAQs written for this city
  faq          jsonb default '[]'::jsonb,

  meta_title_ar       text,
  meta_title_en       text,
  meta_description_ar text,
  meta_description_en text,

  is_published boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz
);

create unique index if not exists city_pages_slug_key on public.city_pages (slug);
create index if not exists city_pages_published_idx
  on public.city_pages (is_published) where is_published;

-- THE GUARD. A row cannot be published without real, city-specific content.
-- 400 characters of intro plus 200 of local context is roughly the point below
-- which a page has nothing a visitor could not get from the generic services
-- page — which is the definition of the thin page we are avoiding.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'city_pages_publish_requires_content'
  ) then
    alter table public.city_pages
      add constraint city_pages_publish_requires_content
      check (
        is_published = false
        or (
          coalesce(length(btrim(intro_ar)), 0) >= 400
          and coalesce(length(btrim(local_context_ar)), 0) >= 200
          and coalesce(length(btrim(meta_title_ar)), 0) > 0
          and coalesce(length(btrim(meta_description_ar)), 0) > 0
        )
      );
  end if;
end $$;

-- Seed the cities worth starting with, UNPUBLISHED. These are the ones with
-- real search demand for this business; the rest of lib/cities.js stays a
-- reference for dropdowns and filters, not a page factory.
insert into public.city_pages (slug, region_id, name_ar, name_en)
select * from (values
  ('riyadh',   'riyadh',  'الرياض',         'Riyadh'),
  ('jeddah',   'makkah',  'جدة',            'Jeddah'),
  ('dammam',   'eastern', 'الدمام',         'Dammam'),
  ('khobar',   'eastern', 'الخبر',          'Khobar'),
  ('makkah',   'makkah',  'مكة المكرمة',    'Makkah'),
  ('madinah',  'madinah', 'المدينة المنورة','Madinah'),
  ('buraydah', 'qassim',  'بريدة',          'Buraydah'),
  ('taif',     'makkah',  'الطائف',         'Taif'),
  ('abha',     'asir',    'أبها',           'Abha'),
  ('tabuk',    'tabuk',   'تبوك',           'Tabuk')
) as seed(slug, region_id, name_ar, name_en)
where not exists (
  select 1 from public.city_pages c where c.slug = seed.slug
);

-- Write the content for one city, then publish it:
--   update public.city_pages
--      set intro_ar = '...', local_context_ar = '...',
--          meta_title_ar = '...', meta_description_ar = '...',
--          is_published = true
--    where slug = 'riyadh';
--
-- If the update is rejected, the content is too thin. That is the constraint
-- doing its job, not a bug. Publish Riyadh, watch it in Search Console, and
-- only then write the next one.
